language: go
sudo: required

go:
  - 1.10.x
  - stable
  - master

before_script:
  # Download test data
  - pushd cs-demos && git lfs pull -I '*' && popd

script:
  # Get list of tests to run with race detection.
  # We don't want to run the entire demo set with it because it's large and race tests take a lot longer.
  - race_tests=$(go test -list . | grep -v "TestDemoSet\|Benchmark" | head -n -1 | awk -vORS=\| '{ print $1 }' | sed 's/|$/\n/')
  # Run race tests
  - go test -v -race -run "$race_tests" -timeout 15m

  # We run all tests again to get full coverage, technically unncecessary tho
  - go test -v -timeout 30m -coverprofile=coverage.txt -coverpkg=$(go list ./... | grep -v msg | awk -vORS=, '{ print $1 }' | sed 's/,$/\n/') ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/511da3cf50cdf951116d
    on_success: change
    on_failure: always
